### ISSUE TITLE
Please add configuration for disabling auto adjusting keyboard backlight

### ISSUE THREAD

**Issue by cshao06** [harttle/macbook-lighter#1]
This tool is great and I'm using it. However, I want to keep my keyboard backlight off all the time. With the auto adjustment systemd unit enabled, it always changes the backlight color.

Thank you!

**Comment by harttle** [comment]
We should make these arguments available in config files.  I'll have a look at it this weekend.

PRs are welcom anyway, I can help to merge publish.

**Comment by harttle** [comment]
Try install the latest version, and set [ML_AUTO_KBD](https://github.com/harttle/macbook-lighter/blob/86ea7efc9914994a850a29583c245c7d88a127f1/macbook-lighter.conf#L28) in your /etc/macbook-lighter.conf to false.

**Comment by cshao06** [comment]
Thanks for the update. I'm not able to install from AUR. It says PKGBUILD not found.

**Comment by harttle** [comment]
My fault, it's fixed now.
